# Generated by Django 4.1.7 on 2023-04-12 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('message', models.CharField(max_length=1500, verbose_name='Message')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='msg.chat', verbose_name='Chat')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
