# Generated by Django 4.1.7 on 2023-04-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_date']},
        ),
    ]
