# Generated by Django 4.1.7 on 2023-04-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_date']},
        ),
    ]
